language: python
python:
  - "2.7"

notifications:
  email: false

sudo: false
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/ExampleHost
  - PLATFORMIO_CI_SRC=examples/ExampleClient
  - PLATFORMIO_CI_SRC=tests/BasicTests

install:
  - pip install -U platformio
  - platformio lib install ArduinoUnit

script:
  - platformio ci --board=sparkfun_fiov3 --lib="."
