language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/ExampleHost
  - PLATFORMIO_CI_SRC=examples/ExampleClient

install:
  - pip install -U platformio

script:
  - platformio ci --board=sparkfun_fiov3 --lib="."
